image: jekyll/jekyll

cache:
  paths:
    - vendor/

before_script:
  - gem i bundler -v 1.17.3
  - bundle config set path 'vendor'

pages:
  stage: deploy
  script:
    - bundle install
    - bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - master

stages:
    - deploy
