# Develop override settings

url: http://localhost:4000

analytics:
  provider: false

comments:
  disqus:
    shortname            : "thiagogomesverissimo"

sass:
  style: expanded

# Conversion
markdown: kramdown
highlighter: rouge
lsi: true
excerpt_separator: ""
incremental: false

# Markdown Processing
kramdown:
  input: GFM

  
