- name: deploy aegir with ansible
  become: yes
  hosts: aegir

  vars:

    # mysql
    mysql_root_username: 'root'
    # senha temporária
    mysql_root_password: "mysql123"
    mysql_users:
      - name: 'aegir_root'
        host: '%'
        password: "aegir123"
        priv: "*.*:ALL,GRANT"

    # aegir
    aegir_db_user: 'root'
    aegir_db_password: "mysql123"
    aegir_db_host: 'localhost'
    aegir_frontend_url: 'aegir.xurepinha.net'
    aegir_makefile_path: 'files/aegir.make'
    aegir_admin_email: 'admin@admin.com'
    aegir_install_drush: false
    aegir_php_version: '7.0'
    aegir_dependencies_php7_0:
      - php7.0
      - php7.0-cli
      - php7.0-common
      - php7.0-gd
      - php7.0-mbstring
      - php7.0-intl
      - php7.0-xml
      - php7.0-curl
      - php7.0-ldap
      - php7.0-mysql

  roles:
    - geerlingguy.mysql
    - ergonlogic.aegir
    - geerlingguy.composer

  post_tasks:

    - name: Configurando senha admin para usuário admin
      shell: 'drush @hostmaster user-password admin --password="admin"'
      become: yes
      become_user: aegir


    - name: Baixa o drupal-8.6.3 com o composer
      become: yes
      become_user: aegir
      composer:
        command: create-project
        arguments: drupal/drupal drupal-8.6.3 8.6.3
        working_dir: /var/aegir/platforms/

Criar alias:
drush provision-save @platform_atriumhead --context_type=platform \
    --root=/var/aegir/atrium-head
salvar:
    drush provision-verify @platform_atriumhead

frontend:
drush @hostmaster hosting-import @contextname
